standardnotes/auth

- package.json
- src/Bootstrap/Container.ts
- src/Bootstrap/Types.ts
- src/Controller/UsersController.spec.ts
- src/Controller/UsersController.ts
- src/Domain/Setting/SettingRepositoryInterface.ts
- src/Domain/Setting/SimpleSetting.ts
- src/Domain/Setting/test/SettingRepositoryStub.ts
- src/Domain/Setting/test/SettingTest.ts
- src/Domain/UseCase/GetSettings/GetSettings.spec.ts
- src/Domain/UseCase/GetSettings/GetSettings.ts
- src/Domain/UseCase/GetSettings/GetSettingsDto.ts
- src/Domain/UseCase/GetSettings/GetSettingsResponse.ts
- src/Domain/UseCase/GetSettings/test/GetSettingsTest.ts
- src/Domain/User/test/UserTest.ts
- src/Domain/Uuid/Uuid.ts
- src/Infra/MySQL/MySQLSettingRepository.spec.ts
- src/Infra/MySQL/MySQLSettingRepository.ts
- src/Projection/SettingProjector.spec.ts
- src/Projection/SettingProjector.ts
[Task](https://app.asana.com/0/1199914526147392/1200004328990526/f)
> GET user settings

- src/Bootstrap/Container.ts
- src/Bootstrap/Types.ts
- src/Controller/UsersController.spec.ts
- src/Controller/UsersController.ts
- src/Controller/test/UsersControllerTest.ts
- src/Domain/Setting/SimpleSetting.ts
- src/Domain/UseCase/GetSetting/GetSetting.spec.ts
- src/Domain/UseCase/GetSetting/GetSetting.ts
- src/Domain/UseCase/GetSetting/GetSettingDto.ts
- src/Domain/UseCase/GetSetting/GetSettingResponse.ts
- src/Domain/UseCase/GetSetting/test/GetSettingTest.ts
- src/Domain/UseCase/GetSettings/GetSettings.spec.ts
- src/Domain/UseCase/GetSettings/GetSettings.ts
- src/Domain/UseCase/GetSettings/GetSettingsResponse.ts
- src/Domain/User/test/data.ts
- src/Projection/SettingProjector.spec.ts
- src/Projection/SettingProjector.ts
- src/Projection/test/SettingProjectorTest.ts
[Task](https://app.asana.com/0/1199914526147392/1200004328990526/f)
> GET user setting by name

- src/Bootstrap/Container.ts
- src/Bootstrap/Types.ts
- src/Controller/AuthController.spec.ts
- src/Controller/AuthController.ts
- src/Domain/UseCase/GetAuthMethods/GetAuthMethods.spec.ts
- src/Domain/UseCase/GetAuthMethods/GetAuthMethods.ts
- src/Domain/UseCase/GetAuthMethods/GetAuthMethodsDto.ts
- src/Domain/UseCase/GetAuthMethods/GetAuthMethodsResponse.ts
- src/Domain/UseCase/GetAuthMethods/test/GetAuthMethodsTest.ts
A prerequisite for [this task](https://app.asana.com/0/1199914526147392/1200004328990530/f).
> feat: GET /auth/methods

- src/Bootstrap/Container.ts
- src/Bootstrap/Types.ts
- src/Controller/UsersController.spec.ts
- src/Controller/UsersController.ts
- src/Controller/test/UsersControllerTest.ts
- src/Domain/Event/DomainEventFactory.spec.ts
- src/Domain/Event/DomainEventFactory.ts
- src/Domain/Event/DomainEventFactoryInterface.ts
- src/Domain/UseCase/DeleteAccount/DeleteAccount.spec.ts
- src/Domain/UseCase/DeleteAccount/DeleteAccount.ts
- src/Domain/UseCase/DeleteAccount/DeleteAccountDTO.ts
- src/Domain/UseCase/DeleteAccount/DeleteAccountResponse.ts
> feat: add deleting accounts

- package.json
- src/Bootstrap/Container.ts
- src/Bootstrap/Types.ts
- src/Controller/AuthController.ts
- src/Controller/UsersController.spec.ts
- src/Controller/UsersController.ts
- src/Controller/test/UsersControllerTest.ts
- src/Domain/Setting/DeleteSettingDto.ts
- src/Domain/Setting/SettingRepositoryInterface.ts
- src/Domain/Setting/test/SettingRepositoryStub.ts
- src/Domain/UseCase/DeleteSetting/DeleteSetting.spec.ts
- src/Domain/UseCase/DeleteSetting/DeleteSetting.ts
- src/Domain/UseCase/DeleteSetting/DeleteSettingDto.ts
- src/Domain/UseCase/DeleteSetting/DeleteSettingResponse.ts
- src/Domain/UseCase/DeleteSetting/test/DeleteSettingTest.ts
- src/Domain/UseCase/GetAuthMethods/GetAuthMethods.ts
- src/Domain/UseCase/GetAuthMethods/GetAuthMethodsResponse.ts
- src/Domain/UseCase/GetSetting/GetSetting.ts
- src/Domain/UseCase/GetSetting/GetSettingResponse.ts
- src/Domain/UseCase/UpdateSetting/UpdateSetting.ts
- src/Domain/UseCase/UpdateSetting/UpdateSettingResponse.ts
- src/Infra/MySQL/MySQLSettingRepository.spec.ts
- src/Infra/MySQL/MySQLSettingRepository.ts
- yarn.lock
[Related task](https://app.asana.com/0/1199914526147392/1200253357617515/f)
> feat: DELETE user setting

- .env.sample
- src/Domain/Encryption/CrypterNode.spec.ts
- src/Domain/Encryption/CrypterNode.ts
- src/Domain/Session/SessionService.spec.ts
- src/Domain/Session/SessionService.ts
[Related task](https://app.asana.com/0/1199914526147392/1200284411286808/f)
> fix: ENCRYPTION_SERVER_KEY must be 32 bytes

- src/Controller/UsersController.spec.ts
- src/Controller/UsersController.ts
[ticket](https://app.asana.com/0/1199914526147392/1200265329674322/f)
> fix: proper success response for PUT settings (no body)

- migrations/1630661830850-fix_encryption_version_on_mfa_settings.ts
- src/Controller/SettingsController.spec.ts
- src/Controller/SettingsController.ts
- src/Domain/Encryption/CrypterNode.spec.ts
- src/Domain/Encryption/CrypterNode.ts
- src/Domain/Setting/Setting.ts
- src/Domain/Setting/SettingFactory.ts
- src/Domain/Setting/SettingService.spec.ts
- src/Domain/Setting/SettingService.ts
- src/Domain/UseCase/GetSettings/GetSettings.ts
Internal link: https://app.asana.com/0/1199914526147392/1200905055978346/f
> fix: mfa settings encryption version

- migrations/1630905831679-add-cancelled-flag.ts
- src/Bootstrap/Container.ts
- src/Bootstrap/Types.ts
- src/Controller/UsersController.spec.ts
- src/Controller/UsersController.ts
- src/Domain/Feature/FeatureService.spec.ts
- src/Domain/Handler/SubscriptionCancelledEventHandler.spec.ts
- src/Domain/Handler/SubscriptionCancelledEventHandler.ts
- src/Domain/Handler/SubscriptionPurchasedEventHandler.spec.ts
- src/Domain/Handler/SubscriptionPurchasedEventHandler.ts
- src/Domain/Handler/SubscriptionRefundedEventHandler.ts
- src/Domain/UseCase/GetUserSubscription/GetUserSubscription.spec.ts
- src/Domain/UseCase/GetUserSubscription/GetUserSubscription.ts
- src/Domain/UseCase/GetUserSubscription/GetUserSubscriptionDto.ts
- src/Domain/UseCase/GetUserSubscription/GetUserSubscriptionResponse.ts
- src/Domain/User/UserSubscription.ts
- src/Domain/User/UserSubscriptionRepositoryInterface.ts
- src/Infra/MySQL/MySQLUserSubscriptionRepository.spec.ts
- src/Infra/MySQL/MySQLUserSubscriptionRepository.ts
https://app.asana.com/0/1199914526147392/1200845194469719/f
> feat: get user subscription endpoint

- bin/server.ts
- package.json
- src/Bootstrap/Container.ts
- src/Bootstrap/Types.ts
- src/Controller/ApiGatewayAuthMiddleware.spec.ts
- src/Controller/ApiGatewayAuthMiddleware.ts
- src/Controller/TokensController.spec.ts
- src/Controller/TokensController.ts
- src/Domain/Auth/AuthenticationMethodResolver.spec.ts
- src/Domain/Auth/AuthenticationMethodResolver.ts
- src/Domain/Auth/TokenDecoder.spec.ts
- src/Domain/Auth/TokenDecoder.ts
- src/Domain/Auth/TokenDecoderInterface.ts
- src/Domain/Subscription/EphemeralToken.ts
- src/Domain/Subscription/EphemeralTokenRepositoryInterface.ts
- src/Domain/UseCase/CreateEphemeralToken/CreateEphemeralToken.spec.ts
- src/Domain/UseCase/CreateEphemeralToken/CreateEphemeralToken.ts
- src/Domain/UseCase/CreateEphemeralToken/CreateEphemeralTokenDTO.ts
- src/Domain/UseCase/CreateEphemeralToken/CreateEphemeralTokenResponse.ts
- src/Infra/Redis/RedisEphemeralTokenRepository.spec.ts
- src/Infra/Redis/RedisEphemeralTokenRepository.ts
- yarn.lock
Internal link: https://app.asana.com/0/1199914526147392/1201095346919841/f
> feat: add creating ephemeral tokens and api-gateway authentication

- src/Bootstrap/Container.ts
- src/Bootstrap/Types.ts
- src/Controller/TokensController.spec.ts
- src/Controller/TokensController.ts
- src/Domain/Subscription/EphemeralTokenRepositoryInterface.ts
- src/Domain/UseCase/AuthenticateToken/AuthenticateToken.spec.ts
- src/Domain/UseCase/AuthenticateToken/AuthenticateToken.ts
- src/Domain/UseCase/AuthenticateToken/AuthenticateTokenDTO.ts
- src/Domain/UseCase/AuthenticateToken/AuthenticateTokenResponse.ts
- src/Infra/Redis/RedisEphemeralTokenRepository.spec.ts
- src/Infra/Redis/RedisEphemeralTokenRepository.ts
Internal link: https://app.asana.com/0/1199914526147392/1201095346919843/f
> feat: add request validation based on an ephemeral token

- src/Controller/FeaturesController.ts
- src/Controller/SettingsController.ts
- src/Controller/UsersController.ts
- src/Controller/WebSocketsController.ts
Internal link: https://app.asana.com/0/1199914526147392/1201095006695751/f
> fix: switch auth middleware to api gateway middleware

- package.json
- src/Bootstrap/Container.ts
- src/Bootstrap/Types.ts
- src/Controller/ApiGatewayOfflineAuthMiddleware.spec.ts
- src/Controller/ApiGatewayOfflineAuthMiddleware.ts
- src/Controller/OfflineController.spec.ts
- src/Controller/OfflineController.ts
- src/Domain/Auth/TokenDecoder.spec.ts
- src/Domain/Auth/TokenDecoder.ts
- src/Domain/Auth/TokenDecoderInterface.ts
- src/Domain/UseCase/AuthenticateOfflineSubscriptionToken/AuthenticateOfflineSubscriptionToken.ts
- src/Domain/UseCase/AuthenticateOfflineSubscriptionToken/AuthenticateOfflineSubscriptionTokenResponse.ts
- src/Domain/UseCase/GetUserOfflineSubscription/GetUserOfflineSubscription.spec.ts
- src/Domain/UseCase/GetUserOfflineSubscription/GetUserOfflineSubscription.ts
- src/Domain/UseCase/GetUserOfflineSubscription/GetUserOfflineSubscriptionDto.ts
- src/Domain/UseCase/GetUserOfflineSubscription/GetUserOfflineSubscriptionResponse.ts
- yarn.lock
Internal link: https://app.asana.com/0/1199914526147392/1201317156714310/f
related to: https://github.com/standardnotes/api-gateway/commit/aa3b9980a37b379b3898cf9ae9e5481d0c646bc2
> feat: get offline subscription for a user

- bin/backup.ts
- docker/entrypoint.sh
- package.json
- src/Domain/Event/DomainEventFactory.spec.ts
- src/Domain/Event/DomainEventFactory.ts
- src/Domain/Event/DomainEventFactoryInterface.ts
- src/Domain/Setting/SettingRepositoryInterface.ts
- src/Infra/MySQL/MySQLSettingRepository.spec.ts
- src/Infra/MySQL/MySQLSettingRepository.ts
- yarn.lock
Part 1 of transfering email backups to a setting
Internal link: https://app.asana.com/0/1201371033937453/1201366388874768/f
> feat: add initiating daily and weekly email backups based on settings

- src/Controller/InternalController.spec.ts
- src/Controller/InternalController.ts
Internal link: https://app.asana.com/0/1201371033937453/1201366388874768/f
> feat: add internal controller for retrieving user setting

- src/Bootstrap/Container.ts
- src/Bootstrap/Types.ts
- src/Domain/Handler/SubscriptionPurchasedEventHandler.spec.ts
- src/Domain/Handler/SubscriptionPurchasedEventHandler.ts
- src/Domain/Handler/SubscriptionReassignedEventHandler.spec.ts
- src/Domain/Handler/SubscriptionReassignedEventHandler.ts
- src/Domain/Handler/SubscriptionRenewedEventHandler.spec.ts
- src/Domain/Handler/SubscriptionRenewedEventHandler.ts
- src/Domain/Setting/SettingService.spec.ts
- src/Domain/Setting/SettingService.ts
- src/Domain/Setting/SettingServiceInterface.ts
- src/Domain/Setting/SettingToSubscriptionMap.spec.ts
- src/Domain/Setting/SettingToSubscriptionMap.ts
- src/Domain/Setting/SettingToSubscriptionMapInterface.ts
Internal link: https://app.asana.com/0/1201371033937453/1201366388874768/f
> feat: add creating default setting upon subscription change

- bin/backup.ts
- src/Domain/Role/RoleService.spec.ts
- src/Domain/Role/RoleService.ts
- src/Domain/Role/RoleServiceInterface.ts
Internal link: https://app.asana.com/0/0/1201519433567354/f
> feat: add checking is user is permitted for daily backups

- .github/pull_request_template.md
- src/Controller/SettingsController.spec.ts
- src/Controller/SettingsController.ts
- src/Domain/Setting/SettingToSubscriptionMap.spec.ts
- src/Domain/Setting/SettingToSubscriptionMap.ts
- src/Domain/Setting/SettingToSubscriptionMapInterface.ts
- src/Domain/UseCase/UpdateSetting/UpdateSetting.spec.ts
- src/Domain/UseCase/UpdateSetting/UpdateSetting.ts
- src/Domain/UseCase/UpdateSetting/UpdateSettingResponse.ts
it will be now verified if the user has permission to change setting of email backups
Internal link: https://app.asana.com/0/0/1201519659473961/f
> feat: add checking if user is permitted to change a setting

- src/Bootstrap/Container.ts
- src/Bootstrap/Types.ts
- src/Controller/SettingsController.spec.ts
- src/Controller/SettingsController.ts
- src/Domain/Setting/SettingRepositoryInterface.ts
- src/Domain/UseCase/MuteFailedBackupsEmails/MuteFailedBackupsEmails.spec.ts
- src/Domain/UseCase/MuteFailedBackupsEmails/MuteFailedBackupsEmails.ts
- src/Domain/UseCase/MuteFailedBackupsEmails/MuteFailedBackupsEmailsDTO.ts
- src/Domain/UseCase/MuteFailedBackupsEmails/MuteFailedBackupsEmailsResponse.ts
- src/Infra/MySQL/MySQLSettingRepository.spec.ts
- src/Infra/MySQL/MySQLSettingRepository.ts
muting failed backups emails endpoint
Internal link: https://app.asana.com/0/0/1201519433567355/f
> feat: add muting failed backups emails

- src/Domain/Setting/SettingService.spec.ts
- src/Domain/Setting/SettingService.ts
When user enables the email backups setting a email backup will be automatically triggered
Internal link: https://app.asana.com/0/0/1201531376182198/f
> feat: trigger email backup upon setting enabling

- src/Domain/Setting/SettingToSubscriptionMap.spec.ts
- src/Domain/Setting/SettingToSubscriptionMap.ts
- src/Domain/Setting/SettingToSubscriptionMapInterface.ts
- src/Domain/UseCase/UpdateSetting/UpdateSetting.spec.ts
- src/Domain/UseCase/UpdateSetting/UpdateSetting.ts
Add a forced encryption version on certain settings
Internal link: https://app.asana.com/0/0/1201538334229419/f
> fix: add default server encryption version for defined settings

- src/Controller/AdminController.spec.ts
- src/Controller/AdminController.ts
_Ability for admin to generate a subscription_token_
Internal link: https://app.asana.com/0/1160983365020104/1201447029184200
> feat: ability to generate subscription tokens via admin

- package.json
- yarn.lock
- update `@standardnotes/features` (https://github.com/standardnotes/snjs/pull/527)
> chore(deps): update @standardnotes/features

- src/Controller/AdminController.spec.ts
- src/Controller/AdminController.ts
ability to generate subscription tokens via admin
Internal link: https://app.asana.com/0/1160983365020104/1201447029184200
> feat: ability to generate subscription tokens via admin (#106)

- .github/workflows/dev.yml
- .github/workflows/prod.yml
- bin/backup.ts
- package.json
- src/Domain/Setting/SettingService.spec.ts
- src/Domain/Setting/SettingService.ts
- src/Domain/Setting/SettingToSubscriptionMap.spec.ts
- src/Domain/Setting/SettingToSubscriptionMap.ts
- src/Infra/MySQL/MySQLSettingRepository.spec.ts
- yarn.lock
Update to latest settings package - main change is the change of `EMAIL_BACKUP` setting name to `EMAIL_BACKUP_FREQUENCY` - /cc @vardan-arm 
N/A
> fix: update auth with latest settings package

- migrations/1640862425427-remove_no_distraction_theme.ts
Remove the no longer needed no-distraction theme
https://app.asana.com/0/0/1201539621830841/f
> fix: remove the no-distraction theme from permissions

- bin/backup.ts
- docker/entrypoint.sh
- package.json
- src/Domain/Event/DomainEventFactory.spec.ts
- src/Domain/Event/DomainEventFactory.ts
- src/Domain/Event/DomainEventFactoryInterface.ts
- yarn.lock
Running daily cloud backups for Dropbox, One Drive and Google Drive based on user settings.
https://app.asana.com/0/1201610838193044/1201547828356723/f
> feat: add daily backups for cloud providers based on user settings

- migrations/1640701224273-add-smart-tags.ts
Add smart filter authentication migration
Related PRs:
- https://github.com/standardnotes/payments/pull/106/files (plus and pro plan)
- https://github.com/standardnotes/snjs/pull/526/files (permission name)
Internal link: https://app.asana.com/0/1201409453293587/1201576223433260
> feat: add smart filters premium

- src/Domain/Setting/SettingService.spec.ts
- src/Domain/Setting/SettingService.ts
Trigger cloud backups upon enabling
https://app.asana.com/0/1201610838193044/1201563763625339/f
> feat: trigger cloud backup upon enabling

- src/Domain/Setting/SettingService.spec.ts
- src/Domain/Setting/SettingService.ts
Fixes an issue where the cloud backup was not trigger upon "perform backup" request.
https://app.asana.com/0/1201610838193044/1201547828356716/f
> fix: triggering cloud backups upon frequency settings updated

- src/Domain/Setting/SettingService.spec.ts
- src/Domain/Setting/SettingService.ts
Fixes the issue where backups were trigger upon disabling the setting
https://app.asana.com/0/1201610838193044/1201646238648902/f
> fix: triggering backups upon disabled setting

- src/Domain/Setting/SettingToSubscriptionMap.ts
Add default sensitivity settings for mute emails settings
-
> fix: add missing non-sensitive settings to defaults

- src/Controller/AdminController.spec.ts
- src/Controller/AdminController.ts
- ability to disable email backups
[Internal link](https://app.asana.com/0/1201611182420182/1201669186126030)
> feat: disable email backups

- package.json
- src/Bootstrap/Container.ts
- src/Bootstrap/Types.ts
- src/Controller/AdminController.spec.ts
- src/Controller/AdminController.ts
- src/Domain/Handler/FileUploadedEventHandler.spec.ts
- src/Domain/Handler/FileUploadedEventHandler.ts
- src/Domain/Setting/SettingService.spec.ts
- src/Domain/Setting/SettingService.ts
- src/Domain/Setting/SettingsAssociationService.spec.ts
- src/Domain/Setting/SettingsAssociationService.ts
- src/Domain/Setting/SettingsAssociationServiceInterface.ts
- src/Domain/UseCase/UpdateSetting/UpdateSetting.spec.ts
- src/Domain/UseCase/UpdateSetting/UpdateSetting.ts
- yarn.lock
Handling file uploaded events by updating the used bytes used quota setting
[Internal link](https://app.asana.com/0/1199942776723820/1201636055949681/f)
> feat: Handle file uploaded events

- package.json
- src/Domain/Handler/ListedAccountCreatedEventHandler.spec.ts
- src/Domain/Handler/ListedAccountCreatedEventHandler.ts
- yarn.lock
Add saving listed secrets as user settings
[Internal link](https://app.asana.com/0/1160985268757888/1201716439397325/f)
> feat: add listed account created event handling

- package.json
- src/Domain/Feature/FeatureService.spec.ts
- src/Domain/Feature/FeatureService.ts
- yarn.lock
> fix: upgrade features dep

- package.json
- yarn.lock
- bump `@standardnotes/features` version to `1.34.3`
[Internal link](https://app.asana.com/0/1201611182420182/1201836690484207)
> chore(deps): bump @standardnotes/features

- migrations/1647421277767-remove_user_agent.ts
- src/Domain/UseCase/ChangeCredentials/ChangeCredentials.spec.ts
- src/Domain/UseCase/ChangeCredentials/ChangeCredentials.ts
- src/Domain/UseCase/Register.ts
- src/Domain/UseCase/UpdateUser.ts
- src/Domain/User/User.ts
Remove storing last used user agent by user for privacy+security reasons.
[Internal link](https://app.asana.com/0/1160985268757888/1201973183942509/f)
> feat: remove storing last used user agent by user

- migrations/1654877423147-add_advanced_checklist_editor_permission.ts
[Internal link](https://app.asana.com/0/1202300765615141/1202346315300571/f)
> feat: add advanced checklist editor permissions
